stages:
  - build
  - deploy

build-job:
  stage: build
  tags:
    - python
  before_script:
    - apk add zip
  script:
    - mkdir public
    - mv ./timebank ./public/timebank
    - mv ./run.py ./public/run.py
    - mv ./requirements.txt ./public/requirements.txt
    - zip -r public.zip public
  artifacts:
    paths:
      - public.zip
  only:
    - main

deploy-job:
  stage: deploy
  tags:
    - python
  before_script:
  - apk add openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no public.zip automation@157.245.27.101:/home/automation/timebank_app
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "pkill python3"
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; rm -r timebank"
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; unzip public.zip"
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; source venv/bin/activate"
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; pip3 install -r requirements.txt"
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; export FLASK_APP=run.py"
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; export FLASK_ENV=development"
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; python3 run.py"

