stages:          # List of stages for jobs, and their order of execution
  - build1
  - deploy
  - build2

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - python
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - binaries/
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  tags:
    - python
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
