stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - python
  before_script:
    - apk add zip
  script:
    - mkdir public
    - cp ./timebank ./public/timebank
    - cd python
    - zip -r public.zip public
  artifacts:
    paths:
#      - ./timebank
#      - ./run.py
#      - ./requirements.txt
      - python.zip
  only:
    - main

deploy-job:
  stage: deploy
  tags:
    - python
  before_script:
  - apk add openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no python.zip automation@157.245.27.101:/home/automation/timebank_app
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "pkill python3"
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; rm -r timebank"
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; unzip python.zip"