stages:
  - build
  - deploy

build-job:
  stage: build
  tags:
    - python
  before_script:
    - apk add zip
  script:
    - zip -r public.zip timebank requirements.txt
  artifacts:
    paths:
      - public.zip
  only:
    - main

deploy-job:
  stage: deploy
  tags:
    - python
  before_script:
  - apk add openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no public.zip automation@157.245.27.101:/home/automation/timebank_app
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "pkill python3"
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; rm -r timebank"
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; rm requirements.txt"
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; unzip public.zip"
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; source venv/bin/activate; pip install -r requirements.txt"
#    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; "
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; source venv/bin/activate; export FLASK_APP=run.py; export FLASK_ENV=development; nohup python3 run.py; pkill -STOP python3; bg; disown; logout"
#    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 pkill -STOP python3
#    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; source venv/bin/activate; python3 run.py"
#    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /home/automation/timebank_app; rm public.zip
    - echo "Program running in background
